pyodbc.cpython-37m-x86_64-linux-gnu.so,sha256=X1A7Dl72C5eIjr2fsGDFBr1iuKbbLejOBqVTKYBuNig,895248
pyodbc-4.0.35.data/data/pyodbc.pyi,sha256=R-lJ63bwP_7ETJL2QFphFJQCCB2tzbon0SBfzNDkBPw,13165
pyodbc-4.0.35.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.35.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-4.0.35.dist-info/WHEEL,sha256=5qaUL7R7UuAgTpV1hnYjoipMHezG5YJtRxtV3_rU2Ew,150
pyodbc-4.0.35.dist-info/RECORD,,
pyodbc-4.0.35.dist-info/METADATA,sha256=eWhyIxFGUQbFUvv_3pG4rhPPywBsNU7TlH2Pf9Yvfqg,2750
