pyodbc.cpython-36m-x86_64-linux-gnu.so,sha256=78r7MAoC-oGkRJVBJPRqBSRh1u4kSeFM5t_q2EssdIk,887040
pyodbc-4.0.35.data/data/pyodbc.pyi,sha256=R-lJ63bwP_7ETJL2QFphFJQCCB2tzbon0SBfzNDkBPw,13165
pyodbc-4.0.35.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.35.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-4.0.35.dist-info/WHEEL,sha256=YVAXCacQXnznQ-_lMj8Nvqrs7YPtMP1pHRCw9EcyWRQ,150
pyodbc-4.0.35.dist-info/RECORD,,
pyodbc-4.0.35.dist-info/METADATA,sha256=uKK9FcB6UlNtSd5jYU-CVFZw1mLbweBxRdZJFVbmIAA,2770
