pyodbc.cpython-311-x86_64-linux-gnu.so,sha256=AlTVeUF06VlNIalb75SNIPvnPGAIAQYxRuavt0UASYg,956704
pyodbc-4.0.35.data/data/pyodbc.pyi,sha256=R-lJ63bwP_7ETJL2QFphFJQCCB2tzbon0SBfzNDkBPw,13165
pyodbc-4.0.35.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.35.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-4.0.35.dist-info/WHEEL,sha256=zcODeksSPXfEVqloqbuxG5DqZN6qJmVdi0EN9bjsiGQ,152
pyodbc-4.0.35.dist-info/RECORD,,
pyodbc-4.0.35.dist-info/METADATA,sha256=eWhyIxFGUQbFUvv_3pG4rhPPywBsNU7TlH2Pf9Yvfqg,2750
